services:
  postgresql:
    image: postgres:16
    container_name: booklub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: booklub
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql/data
    networks:
      - booklub-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=booklub-postgres  # Ensure this is the service name
      - KC_DB_URL_DATABASE=booklub
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=1234
      - KC_DB_URL_PORT=5432
    ports:
      - "8080:8080"
    command: ["start-dev"]
    depends_on:
      - postgresql
    networks:
      - booklub-network

  minio:
    image: quay.io/minio/minio
    container_name: booklub-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker-volumes/minio:/data
    command: server /data --console-address ":9001"

networks:
  booklub-network:

