services:
  postgresql:
    image: postgres:16
    container_name: booklub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: booklub
    ports:
      - '5432:5432'
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql/data