FROM quay.io/keycloak/keycloak:26.2

COPY docker/keycloak/realm-export.json /opt/keycloak/data/import/realm-export.json

LABEL org.opencontainers.image.title="booklub-api-keycloak"
LABEL org.opencontainers.image.description="Keycloak image for deployment"
LABEL org.opencontainers.image.environment="KEYCLOAK_ADMIN, KEYCLOAK_ADMIN_PASSWORD, KC_DB, KC_DB_URL, KC_DB_USERNAME, KC_DB_PASSWORD"

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm", "--features=scripts", "--spi-scripting-scripts-enabled=true"]
