ALTER TABLE club_pending_entries
    DROP CONSTRAINT FK_CLUB_PENDING_ENTRIES_ON_CLUB;

ALTER TABLE club_pending_entries
    DROP CONSTRAINT FK_CLUB_PENDING_ENTRIES_ON_USER;

ALTER TABLE club_pending_entries
    ADD CONSTRAINT FK_CLUB_PENDING_ENTRIES_ON_CLUB FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE CASCADE;

ALTER TABLE club_pending_entries
    ADD CONSTRAINT FK_CLUB_PENDING_ENTRIES_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id) ON DELETE CASCADE;